//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneMedify.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PatientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatientResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneMedify.Resources.PatientResources", typeof(PatientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultProfileImage.png.
        /// </summary>
        public static string CommonProfilePictureName {
            get {
                return ResourceManager.GetString("CommonProfilePictureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StaticFiles\\DefaultProfileImage.png.
        /// </summary>
        public static string CommonProfilePicturePath {
            get {
                return ResourceManager.GetString("CommonProfilePicturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Registration Failed..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Issues.
        /// </summary>
        public static string InternalServerIssue {
            get {
                return ResourceManager.GetString("InternalServerIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error..
        /// </summary>
        public static string InternalServerResponse {
            get {
                return ResourceManager.GetString("InternalServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date of Birth.
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Disease Id..
        /// </summary>
        public static string InvalidDiseaseId {
            get {
                return ResourceManager.GetString("InvalidDiseaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot select more than 3 disease..
        /// </summary>
        public static string InvalidDiseaseIdCount {
            get {
                return ResourceManager.GetString("InvalidDiseaseIdCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageIndex should not be less than 0..
        /// </summary>
        public static string InvalidPageIndex {
            get {
                return ResourceManager.GetString("InvalidPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid weight..
        /// </summary>
        public static string InvalidWeight {
            get {
                return ResourceManager.GetString("InvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email id already exist..
        /// </summary>
        public static string IsUniqueEmail {
            get {
                return ResourceManager.GetString("IsUniqueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this mobile number already exist..
        /// </summary>
        public static string IsUniqueMobileNo {
            get {
                return ResourceManager.GetString("IsUniqueMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert multiple disease with same Id..
        /// </summary>
        public static string MultipleDisease {
            get {
                return ResourceManager.GetString("MultipleDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to Update..
        /// </summary>
        public static string NothingToUpdate {
            get {
                return ResourceManager.GetString("NothingToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details not updated..
        /// </summary>
        public static string PatientUpdateFailed {
            get {
                return ResourceManager.GetString("PatientUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details updated successfully..
        /// </summary>
        public static string PatientUpdateSuccess {
            get {
                return ResourceManager.GetString("PatientUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Registered Successfully..
        /// </summary>
        public static string SignUpSuccess {
            get {
                return ResourceManager.GetString("SignUpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor&apos;s mobile number does not exist..
        /// </summary>
        public static string UnregisteredDoctorMobileNumber {
            get {
                return ResourceManager.GetString("UnregisteredDoctorMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient&apos;s mobile number does not exist..
        /// </summary>
        public static string UnregisteredPatientMobileNumber {
            get {
                return ResourceManager.GetString("UnregisteredPatientMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number does not exist..
        /// </summary>
        public static string UnregisteredPharmacyMobileNumber {
            get {
                return ResourceManager.GetString("UnregisteredPharmacyMobileNumber", resourceCulture);
            }
        }
    }
}
