//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneMedify.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PharmacyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PharmacyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneMedify.Resources.PharmacyResources", typeof(PharmacyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultProfileImage.png.
        /// </summary>
        public static string CommonProfilePictureName {
            get {
                return ResourceManager.GetString("CommonProfilePictureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\StaticFiles\DefaultProfileImage.png.
        /// </summary>
        public static string CommonProfilePicturePath {
            get {
                return ResourceManager.GetString("CommonProfilePicturePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email id already exist..
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Issues.
        /// </summary>
        public static string InternalServerIssue {
            get {
                return ResourceManager.GetString("InternalServerIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error..
        /// </summary>
        public static string InternalServerResponse {
            get {
                return ResourceManager.GetString("InternalServerResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid CityId..
        /// </summary>
        public static string InvalidCityId {
            get {
                return ResourceManager.GetString("InvalidCityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Establishment Date..
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Format..
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Type..
        /// </summary>
        public static string InvalidFileExtension {
            get {
                return ResourceManager.GetString("InvalidFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file should not be more than 3MB..
        /// </summary>
        public static string InvalidFileLength {
            get {
                return ResourceManager.GetString("InvalidFileLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageIndex should not be less than 0..
        /// </summary>
        public static string InvalidPageIndex {
            get {
                return ResourceManager.GetString("InvalidPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this mobile number already exist..
        /// </summary>
        public static string MobileNumberExists {
            get {
                return ResourceManager.GetString("MobileNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to Update..
        /// </summary>
        public static string NothingToUpdate {
            get {
                return ResourceManager.GetString("NothingToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy Registration failed..
        /// </summary>
        public static string PharmacyRegistrationFailed {
            get {
                return ResourceManager.GetString("PharmacyRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy Registered Successfully..
        /// </summary>
        public static string PharmacyRegistrationSuccess {
            get {
                return ResourceManager.GetString("PharmacyRegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details not updated..
        /// </summary>
        public static string PharmacyUpdateFailed {
            get {
                return ResourceManager.GetString("PharmacyUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details updated successfully..
        /// </summary>
        public static string PharmacyUpdateSuccess {
            get {
                return ResourceManager.GetString("PharmacyUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy&apos;s mobile number does not exist..
        /// </summary>
        public static string UnregisteredPharmacyMobileNumber {
            get {
                return ResourceManager.GetString("UnregisteredPharmacyMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Success..
        /// </summary>
        public static string ValidationSuccess {
            get {
                return ResourceManager.GetString("ValidationSuccess", resourceCulture);
            }
        }
    }
}
