//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneMedify.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrescriptionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrescriptionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneMedify.Resources.PrescriptionResource", typeof(PrescriptionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not take action against prescription which is not in pending state..
        /// </summary>
        public static string ActionCanNotBeTaken {
            get {
                return ResourceManager.GetString("ActionCanNotBeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription Approved.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Prescription has been approved.
        /// </summary>
        public static string ApproveEmail {
            get {
                return ResourceManager.GetString("ApproveEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription created successfully..
        /// </summary>
        public static string CreatedSuccessfully {
            get {
                return ResourceManager.GetString("CreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription not created..
        /// </summary>
        public static string CreationFailed {
            get {
                return ResourceManager.GetString("CreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease passed in prescription does not exist..
        /// </summary>
        public static string DiseaseNotExistById {
            get {
                return ResourceManager.GetString("DiseaseNotExistById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add medicine for selected disease..
        /// </summary>
        public static string DiseaseNotHaveMedicine {
            get {
                return ResourceManager.GetString("DiseaseNotHaveMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor is busy.
        /// </summary>
        public static string DoctorBusy {
            get {
                return ResourceManager.GetString("DoctorBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor’s mobile number does not exist..
        /// </summary>
        public static string DoctorNotExistByMobile {
            get {
                return ResourceManager.GetString("DoctorNotExistByMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription Expired.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date..
        /// </summary>
        public static string InvalidExpiryDate {
            get {
                return ResourceManager.GetString("InvalidExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid numbers of days..
        /// </summary>
        public static string InvalidMedicineDays {
            get {
                return ResourceManager.GetString("InvalidMedicineDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only enter 1 or 2..
        /// </summary>
        public static string InvalidMedicineDosage {
            get {
                return ResourceManager.GetString("InvalidMedicineDosage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid medicine timing..
        /// </summary>
        public static string InvalidMedicineTiming {
            get {
                return ResourceManager.GetString("InvalidMedicineTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mobile number..
        /// </summary>
        public static string InvalidMobileFormat {
            get {
                return ResourceManager.GetString("InvalidMobileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageIndex should not be less than 0..
        /// </summary>
        public static string InvalidPageIndex {
            get {
                return ResourceManager.GetString("InvalidPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid medicine passed which does not belongs to any passed diseases..
        /// </summary>
        public static string MedicineNotBelongsToDisease {
            get {
                return ResourceManager.GetString("MedicineNotBelongsToDisease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient&apos;s Mobile Number does not exist.
        /// </summary>
        public static string MobileNumberExists {
            get {
                return ResourceManager.GetString("MobileNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient&apos;s Mobile Number is not valid.
        /// </summary>
        public static string MobileNumberIsValid {
            get {
                return ResourceManager.GetString("MobileNumberIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription should have medicine..
        /// </summary>
        public static string NoMedicineAdded {
            get {
                return ResourceManager.GetString("NoMedicineAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient’s mobile number does not exist..
        /// </summary>
        public static string PatientNotExistByMobile {
            get {
                return ResourceManager.GetString("PatientNotExistByMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .pdf.
        /// </summary>
        public static string PdfFileExtension {
            get {
                return ResourceManager.GetString("PdfFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy’s mobile number does not exist..
        /// </summary>
        public static string PharmacyNotExistByMobile {
            get {
                return ResourceManager.GetString("PharmacyNotExistByMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription is Approved.
        /// </summary>
        public static string PrescriptionApproved {
            get {
                return ResourceManager.GetString("PrescriptionApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription Id does not exist..
        /// </summary>
        public static string PrescriptionNotExistById {
            get {
                return ResourceManager.GetString("PrescriptionNotExistById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription id does not exist..
        /// </summary>
        public static string PrescriptionNotExistsById {
            get {
                return ResourceManager.GetString("PrescriptionNotExistsById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription is Rejected.
        /// </summary>
        public static string PrescriptionRejected {
            get {
                return ResourceManager.GetString("PrescriptionRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription Rejected.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Prescription has been rejected.
        /// </summary>
        public static string RejectEmail {
            get {
                return ResourceManager.GetString("RejectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not pass the same disease multiple times..
        /// </summary>
        public static string SameDiseaseIds {
            get {
                return ResourceManager.GetString("SameDiseaseIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not pass the same medicine multiple times..
        /// </summary>
        public static string SameMedicineIds {
            get {
                return ResourceManager.GetString("SameMedicineIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription is not eligible for send for approval..
        /// </summary>
        public static string SendForApprovalEligibility {
            get {
                return ResourceManager.GetString("SendForApprovalEligibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updation Failed.
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription uploaded successfully..
        /// </summary>
        public static string UploadedSuccessfully {
            get {
                return ResourceManager.GetString("UploadedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription not uploaded..
        /// </summary>
        public static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
    }
}
